### ISSUE TITLE
Stored procedures missing

### ISSUE THREAD

**Issue by spdvi** [PereReynes19/Adventure_Works-DI03#1]
I can´t test the app without the stored procedures.
Please upload them in a single .sql file to this repository.
Thanks

**Comment by PereReynes19** [comment]
Si te lo envié ahora, gracias.

Missatge de Mike Garcia <notifications@github.com> del dia dl., 8 de febr.
2021 a les 20:07:

**Comment by spdvi** [comment]
That works now. Thanks again!
